version: 2
jobs:
  test:
    docker:
      - image: node:10
    workding_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm install
      - run: npm test
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

  build_and_push_latest:
    machine: true
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Build image and push to Quay with tag latest
          command: |
            docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
            docker build -t quay.io/appvia_hub_dev/test-app:$CIRCLE_SHA1 .
            docker tag quay.io/appvia_hub_dev/test-app:$CIRCLE_SHA1 quay.io/appvia_hub_dev/test-app:latest
            docker push quay.io/appvia_hub_dev/test-app:$CIRCLE_SHA1
            docker push quay.io/appvia_hub_dev/test-app:latest

workflows:
  version: 2
  main:
    jobs:
      - test
      - build_and_push_latest:
          requires:
            - test
          filters:
            branches:
              only:
                - master
            tags:
              ignore: /.*/

