version: 2
jobs:
  test:
    docker:
      - image: cirlceci/node:10.15.3
    steps:
      - checkout
      - run: npm test

  build_and_push_latest:
    machine: true
    parallelism: 1
    steps:
      - checkout
      - run:
          name: Build image and push to Quay with tag latest
          command: |
            docker login quay.io --username $QUAY_USERNAME --password $QUAY_PASSWORD
            docker build -t quay.io/appvia_hub_dev/test-app:$CIRCLE_SHA1 .
            docker tag quay.io/appvia_hub_dev/test-app:$CIRCLE_SHA1 quay.io/appvia_hub_dev/test-app:latest
            docker push quay.io/appvia_hub_dev/test-app:$CIRCLE_SHA1
            docker push quay.io/appvia_hub_dev/test-app:latest

workflow:
  version: 2
  jobs:
    - test
    - build_and_push_latest:
      requires:
        - test
      filters:
        branches:
          only:
            - master
        tags:
          ignore: /.*/

